Added new error to raw sending API - MissingFromAddress as distinct from UnauthenticatedFromAddress
postalhq/postal pull request #542
Opened 2018-03-25 16:12 UTC by matthewbloch

This new error would have saved me a couple of hours understanding what I was doing wrong in this issue: https://github.com/atech/postal/issues/530

2018-03-25 16:21 UTC, willpower232 commented
Please could you change it to "FromAddressMissing" for parity with the exception defined here: https://github.com/atech/postal/blob/8b7bcd9a6a3f68051f76e81385f39ede1850e4f6/api/controllers/send_api_controller.rb#L30

2018-03-26 09:52 UTC, willpower232 commented
Thanks, hopefully someone from atech can get it merged soon along with the others

2020-10-01 11:47 UTC, catphish requested changes

2020-10-01 11:47 UTC, catphish commented on api/controllers/send_api_controller.rb
> +        if mail.from.nil? || mail.from.empty? || !/@/.match(mail.from.first)
I would suggest removing the regex check. The from address is not "missing" if it's merely invalid. Also, I assume we have Rails extensions and could therefore just use `mail.from.blank?`

2021-07-27 22:12 UTC, adamcooke commented
I'm planning an API rewrite and am now reluctant to change the behaviour of the old one. The new one will include something like this.

2021-07-27 22:12 UTC, closed without merging